-- custom
--[[if SERVER then
	resource.AddFile("materials/trails/angry.vmt");
resource.AddFile("materials/trails/arrow.vmt");
resource.AddFile("materials/trails/ben.vmt");
resource.AddFile("materials/trails/carebear.vmt");
resource.AddFile("materials/trails/epiclulz.vmt");
resource.AddFile("materials/trails/handy.vmt");
resource.AddFile("materials/trails/happy.vmt");
resource.AddFile("materials/trails/litfuse.vmt");
resource.AddFile("materials/trails/rainbow.vmt");
resource.AddFile("materials/trails/smouch.vmt");
resource.AddFile("materials/trails/star.vmt");
resource.AddFile("materials/trails/wots.vmt");
resource.AddFile("materials/trails/apple.vmt");
resource.AddFile("materials/trails/ban.vmt");
resource.AddFile("materials/trails/bikecat.vmt");
resource.AddFile("materials/trails/checker.vmt");
resource.AddFile("materials/trails/dickspam.vmt");
resource.AddFile("materials/trails/dumb.vmt");
resource.AddFile("materials/trails/facepunch.vmt");
resource.AddFile("materials/trails/film.vmt");
resource.AddFile("materials/trails/firefox.vmt");
resource.AddFile("materials/trails/funny.vmt");
resource.AddFile("materials/trails/gmod.vmt");
resource.AddFile("materials/trails/hurt.vmt");
resource.AddFile("materials/trails/jerry.vmt");
resource.AddFile("materials/trails/kramer.vmt");
resource.AddFile("materials/trails/luaking.vmt");
resource.AddFile("materials/trails/money.vmt");
resource.AddFile("materials/trails/mooninite.vmt");
resource.AddFile("materials/trails/mooninite2.vmt");
resource.AddFile("materials/trails/music.vmt");
resource.AddFile("materials/trails/neon.vmt");
resource.AddFile("materials/trails/OIFY.vmt");
resource.AddFile("materials/trails/omg.vmt");
resource.AddFile("materials/trails/orly.vmt");
resource.AddFile("materials/trails/peace.vmt");
resource.AddFile("materials/trails/pedo.vmt");
resource.AddFile("materials/trails/pencil.vmt");
resource.AddFile("materials/trails/piano.vmt");
resource.AddFile("materials/trails/plaid.vmt");
resource.AddFile("materials/trails/ps3.vmt");
resource.AddFile("materials/trails/rainbow.vmt");
resource.AddFile("materials/trails/ROFL.vmt");
resource.AddFile("materials/trails/shoop.vmt");
resource.AddFile("materials/trails/spam.vmt");
resource.AddFile("materials/trails/steam.vmt");
resource.AddFile("materials/trails/strange.vmt");
resource.AddFile("materials/trails/unfriendly.vmt");
resource.AddFile("materials/trails/wii.vmt");
resource.AddFile("materials/trails/wrong.vmt");
resource.AddFile("materials/trails/wtf.vmt");
resource.AddFile("materials/trails/xbox.vmt");
resource.AddFile("materials/trails/giggity.vmt");
end
]]

ES:AddTrail ("Angry",">:(",560,"trails/angry.vmt");
ES:AddTrail ("Arrow","Point at stuff",480,"trails/arrow.vmt");
ES:AddTrail ("Carebear","Cutie",500,"trails/carebear.vmt");
ES:AddTrail ("Epiclulz","Epic!",1600,"trails/epiclulz.vmt");
ES:AddTrail ("Handy","Not really.",390,"trails/handy.vmt");
ES:AddTrail ("Happy",":)",1500,"trails/happy.vmt");
ES:AddTrail ("Gay pride","For the proud homosexual",3600,"trails/rainbow.vmt");
ES:AddTrail ("Smouch","I don't know",500,"trails/smouch.vmt");
ES:AddTrail ("Star","Love the spotlight.",560,"trails/star.vmt");
ES:AddTrail ("W O T S","I survived",590,"trails/wots.vmt");
ES:AddTrail ("Apple","Very expensive but totally worth it.",4600,"trails/apple.vmt");
ES:AddTrail ("Ban","You don't want this.",680,"trails/ban.vmt");
ES:AddTrail ("Bikecat","...",700,"trails/bikecat.vmt");
ES:AddTrail ("Checker","Check",690,"trails/checker.vmt");
ES:AddTrail ("Dickspam","...",1650,"trails/dickspam.vmt");
ES:AddTrail ("Dumb","Kill yourself.",360,"trails/dumb.vmt");
ES:AddTrail ("Facepunch","For proud members",3200,"trails/facepunch.vmt");
ES:AddTrail ("Film","A true classic.",710,"trails/film.vmt");
ES:AddTrail ("Firefox","Chrome is better.",320,"trails/firefox.vmt");
ES:AddTrail ("Funny","Not that funny.",700,"trails/funny.vmt");
ES:AddTrail ("Gmod","JBMod rules",630,"trails/gmod.vmt");
ES:AddTrail ("Hurt","...",234,"trails/hurt.vmt");
ES:AddTrail ("Jerry","It's Jerry.",1200,"trails/jerry.vmt");
ES:AddTrail ("Kramer","It's Kramer.",1200,"trails/kramer.vmt");
ES:AddTrail ("Excl","Created especially for Excl.",15000,"trails/luaking.vmt");
ES:AddTrail ("Cashmonneyy","Bahooza",450,"trails/money.vmt");
ES:AddTrail ("Laser 2","The new laser trail",120,"trails/mooninite.vmt");
ES:AddTrail ("Mooninite","...",510,"trails/mooninite2.vmt");
ES:AddTrail ("Mooninite 2","...",1580,"trails/music.vmt");
ES:AddTrail ("Neon","Neom beam.",610,"trails/neon.vmt");
ES:AddTrail ("OIFY","Internet",6100,"trails/OIFY.vmt");
ES:AddTrail ("O M G","Oh, my god!",1480,"trails/omg.vmt");
ES:AddTrail ("Oh really","Lolcats.",480,"trails/orly.vmt");
ES:AddTrail ("Peace","Smoke weed erryday.",480,"trails/peace.vmt");
ES:AddTrail ("Pedo","HIDE YO CHILDREN",480,"trails/pedo.vmt");
ES:AddTrail ("Pencil","Artistic",480,"trails/pencil.vmt");
ES:AddTrail ("Piano","For the true maestro.",480,"trails/piano.vmt");
ES:AddTrail ("Plaid","...",480,"trails/plaid.vmt");
ES:AddTrail ("PS3","PS3 supporter",240,"trails/ps3.vmt");
ES:AddTrail ("ROFL","The see me rollin'...",250,"trails/ROFL.vmt");
ES:AddTrail ("Shoop","Da whoop",290,"trails/shoop.vmt");
ES:AddTrail ("Spam","Spammmm",460,"trails/spam.vmt");
ES:AddTrail ("Steam","Gabe is 50.",610,"trails/steam.vmt");
ES:AddTrail ("Strange","For weird people.",760,"trails/strange.vmt");
ES:AddTrail ("Unfriendly","Fuck you too.",812,"trails/unfriendly.vmt");
ES:AddTrail ("Wii","Wii supporter",290,"trails/wii.vmt");
ES:AddTrail ("Wrong","You are wrong.",800,"trails/wrong.vmt");
ES:AddTrail ("WTF","WTF",530,"trails/wtf.vmt");
ES:AddTrail ("Xbox","Xbox supporter.",490,"trails/xbox.vmt");
ES:AddTrail ("Giggity","Unfunny and annoying trail.",800,"trails/giggity.vmt");